### ISSUE TITLE
SweetAltert - Add "custom positioned dialog" & custom font/ font size

### ISSUE THREAD

**Issue by McGeifer** [rajsite/webvi-experiments#3]
Hello!

First of all, thank you for the nice work with this add-on.
There are two features I would love to see in the future, unfortunately my Java knowledge is very limited so I need someone to do this for me :)

1. Would it be possible to extend the functionality with "custom positioned dialogues"?
2. Add a simple way to change the font and the font size for the shown messages.

Best regards

**Comment by rajsite** [comment]
Hi McGeifer!

Thank you and I'm glad you enjoy working with the library!

I pushed a change to add support for SweetAlert's position property and a few more properties for timeouts, etc. You actually don't need to write any JS if you are adding support for properties that are part of the [SweetAlert configuration](https://sweetalert2.github.io/#configuration). You can how the change looks in the Modal Window Options VI that was added or look at the other existing Options VIs.

Configuring styles takes a couple more steps you can see how the MySweetAlertStyles.gcomp is used to create a style theme for a dialog. The pattern shows how to create a reusable Library Component for the style and gives you the ability to fully configure any of the CSS properties for different parts of a dialog. The example does specifically show how to customize the font.

**Comment by rajsite** [comment]
One more thing! To avoid fracturing the conversation too much I went ahead and posted the example to the NI forums: https://forums.ni.com/t5/Example-Programs/SweetAlert-Highly-configurable-popups-for-WebVIs-in-LabVIEW-NXG/ta-p/4011222

If it's not too much trouble we can continue the conversation there. I'll go ahead and close out this issue.
